const data = [
    {
        "title":"1-Habilidades Cognitivas/Intelectuais",
        "values":["Tende a ter inteligência de acima da média a excepcional, frequentemente (mas não sempre) com divisões significativas entre as habilidades de raciocínio verbal e perceptual, velocidades mais baixas de memória de trabalho e/ou processamento, dificuldades de aprendizagem (por exemplo, discalculia, dislexia, dificuldade na compreensão de leitura).", " Memória de longo prazo mais forte", "Memória de Curto prazo mais fraca", " Pode precisar de ajustes acadêmicos na Universidade", "Um perfil de aprendizagem distinto, constituído por picos de pontos fortes e fracos. Dificuldades/diferenças na aprendizagem", "Pode ser atormentada por pensamentos negativos rígidos, estilo de Pensamento preto ou branco, inflexível"]
    },
    {
        "title":"2-Educação/Vida Universitária ",
        "values":["Pode ter largado o ensino médio e voltado depois, ou repetido um ano. Pode Ter graduações não terminadas ou parciais, pode ter terminado várias graduações, muitas têm doutorado. Podem ter levado mais tempo para Atingir seu nível educacional em comparação com seus colegas.", "Pode ter histórico em se matricular e frequentar disciplinas na universidade, Para em seguida trancar disciplinas ou semestres. Algum tempo depois, ela Se re-matricula/frequenta mais tarde. Usualmente isso acontece por ela Estar sobrecarregada. Também é comum um histórico de adiar Exames/provas, não comparecer ás aulas e desistir de disciplinas ou Programas", "Pode ter repetido o ensino médio ou cursos OU largado estes Completamente", "Um histórico de muitos médicos e visitas a orientadores durante a vida Universitária, sem uma melhora significativa", "Dificuldade ao fazer a mesma quantidade de cursos ou disciplinas que seus Colegas", "Pode se perder facilmente no campus, perder objetos, chegar atrasada para Classes ou provas"]
    },
    {
        "title":"3-Carreira/Trabalho",
        "values":["Frequentemente é atraída por profissões que envolvem ajudar outras Pessoas, arte ou animais, frequentemente é “expert” na carreira escolhida. Conheço muitas Mulheres Aspies bem-sucedidas nas seguintes carreiras: Artistas, cantoras, atrizes, poetas, escritoras, professoras, psicólogas, Psiquiatras, consultoras/professoras de pessoas com necessidades Especiais, treinadoras de cavalos, médicas, cientistas, contadoras, Autoras, babás, modelos, comediantes, especialistas em computadores, Tratadoras de animais ou trabalhando em zoológicos, professoras em Universidade, enfermeiras, psíquicas/médiuns, empresárias e fotógrafas", " Pode perder dias de trabalho devido à exaustão social", " Pode ter grandes dificuldades para comparecer/participar de reuniões, Almoços e eventos sociais do trabalho", " Pode inventar desculpas para não cumprir funções no trabalho", " Pode ter um histórico de não conseguir lidar com o ambiente de Trabalho/emprego, frequentemente indo de trabalho em trabalho, Especialmente nos primeiros anos da vida adulta", " Trabalhadora assídua e dedicada", "  Pode ficar estressada se tiver muito trabalho para fazer em um curto Espaço de tempo", "Pode ficar frustrada/estressada se a pedem para fazer muitas coisas ao Mesmo tempo", "Tenta com muito esforço evitar cometer erros e esquecer coisas", " Se esforça para agradar os outros", " Pode se demitir ou terminar relacionamentos sem aviso prévio"]
    },
    {
        "title":"4-Social e Amizades/Relacionamentos",
        "values":["Preferência por interações sociais um-a-um, tendo uma única amizade Próxima", "Precisa de mais tempo afastada de pessoas do que seus pares (solidão)", "Pode ficar confusa em situações de grupos sociais", "Prefere conversar sobre seus interesses especiais", "Realmente não gosta de ‘papo fiado’ ou conversas que não possuem uma Função ou propósito", "Histórico de sofrer bullying, ser provocada, deixada de lado e/ou não se Adequando a colegas de mesma idade, a menos que ela tenha amigos Aspies", "Forte antipatia por conversa fiada, fofocas, coisas sem sentido, mentidas", "Desgosto intenso por mentiras, apesar de poder mentir", "Tem habilidade em socializar, mas é incapaz de o fazer por longos períodos De tempo. Sofre de “exaustão social” ou de uma “ressaca social” quando Socializa por muito tempo. A ressaca pode durar de algumas horas a alguns Dias, o que pode ser debilitante", "Tem grandes dificuldades em conflitos, discussões, quando alguém grita Com ela, brigas, guerra", "Tem muita dificuldade em se afirmar, pedir ajuda, estabelecer limites", "Pode precisar beber para ser sociável", "Pode ter atualmente ou no passado transtorno de estresse pós-traumático, Por ser mal compreendida, mal diagnosticada, maltratada e/ou medicada Erroneamente", " Diferentes habilidades sociais—é excepcionalmente boa em conversa um-a-Um e apresentando para grupos, mas tem dificuldades trabalhando em Situações de grupos", "Pode se achar em situações sociais ou relacionamentos em que ela se sente Infeliz, mas não sabe como sair deles", "Histórico de outros tirarem vantagem dela, apesar de ela seguir Apropriadamente os conselhos de negócios, legais ou sociais das outras Pessoas", "Frequentemente entediada em situações sociais ou festas e/ou não sabe Como agir em situações sociais", "Pode aceitar ir em eventos sociais, e mais tarde inventar uma desculpa do Porque ela não pode ir, frequentemente ficando em casa sozinha", " Frequentemente prefere se dedicar ao seu interesse especial, ao invés de Socializar", " Pode ser considerada a “ovelha negra” da família", " Outras pessoas a consideram diferente, estranha e excêntrica", " Pode sentir como se tivesse que agir “normalmente” para agradar os Outros OU não se importa nada em ser adequada", " Copia, imita, atua para se adaptar e fazer os outros gostarem dela", " Tenta agradar os outros, mas pode fazer coisas extremas de repente (por Exemplo, terminar relacionamentos)", "  Mulheres parecem ser melhores que homens mascarando os traços do Autismo em situações sociais. Apesar disso, mulheres são menos Habilidosas ao fazer isso em situações não familiares", "Pode ser considerada uma pessoa solitária, pode ter muitos conhecidos, Mas não amigos de verdade"]
    },
    {
        "title":"5-Comunicação",
        "values":["Dificuldades ao comunicar seus pensamentos e sentimentos, em palavras, Para outros, especialmente se estiver ansiosa, estressada ou chateada. Frequentemente ela pode digitar ou escrever seus pensamentos muito Melhor", "Pode não gostar de pedir ajuda para os outros, sendo incapaz de pedir Ajuda para os outros, sendo incapaz de pedir ajuda ou não sabendo Como pedir ajuda", "Pode ser passiva, não sabendo estabelecer limites", "Pode ofender outras pessoas dizendo o que pensa, mesmo que ela não Não tenha a intenção", "Pode apontar erros dos outros", "Pode dar muitos detalhes e acabar entediando os outros sem querer", "Pode fazer perguntas embaraçosas (usualmente quando é mais nova)", "Voz incomum (monótona, muito aguda, parecida com voz de criança)", "Tendência a interpretar coisas literalmente, não entendendo o que a Pessoa está tentando dizer", "Pode falar muito alto ou muito baixo, frequentemente sem perceber que Está tentando dizer", "Fica surpresa quando outras pessoas dizem que ela está sendo rude ou Inapropriada"]
    },
    {
        "title":"6A-Fisiologia/Neurologia - Muito Sensível",
        "values":["Sensibilidade muito alta, pode não ser capaz de ouvir ou ver notícias,Ouvir rádio, ler jornal, assistir shows/filmes violentos ou filmes de Terror, ver animais machucados ou feridos, abuso, guerra, trauma, é Sensível ás emoções e “atmosfera emotiva” do ambiente"]
    },
    {
        "title":"6B-Fisiologia/Neurologia - Desordem/Condição do Processamento Sensorial",
        "values":["Pode ter sensibilidade sensorial nas seguintes áreas: audição, visão, Paladar, ato, olfato, equilíbrio, movimento", "Pode ser muito sensível a dor ou ter grande resistência a ela", "Pode se importar com o gosto ou textura da comida, e um pode ser mais Importante que o outro", "Pode ser desastrada ou descoordenada", "Pode não gostar de barulhos altos e/ou se sentir sobrecarregada ou Estressada por luzes brilhantes, cheiros fortes, tecidos/roupas Ásperos ou sirenes passando por perto", "Pode achar crianças difíceis de lidar por causa do choro, gritos e outros Barulhos altos", "Sensível com a textura das roupas e isso é mais importante do que a Aparência delas", "Pode ter que se retirar, se isolar ou isolar outras pessoas quando dica Sobrecarregado pelos sentidos", " Pode não ser capaz de tolerar sons, visões, cheiros, texturas, Movimentos que ela não gosta", "  Pode não gostar de ser abraçada, acariciada ou segurada. “Só gosto de Abraçar se a decisão é minha”", "  Pode ficar chateada ou incomodada se impedida de seguir uma rota Familiar quando vai para algum lugar", "  Coisas que deviam ser doloridas podem não o ser (se machuca e Não sabe como aconteceu)", "   Sistema nervoso tende a se sobrecarregar facilmente, levando a um Retrocesso (por exemplo, ir para um canto quieto em uma festa)", , "  Fome muito grande pode deixa-la de mau-humor e/ou afetar Habilidade de foco", "   Ela pode notar e gostar de fragrâncias, gostos, sons, trabalhos Artísticos e peças de música delicados ou finos"]
    },
    {
        "title":"6C-Fisiologia/Neurologia - Pesquisas recentes com escaneamento do cérebro apronta para um papel maior da Amigdala causando maior emoções, ansiedade e raiva",
        "values":["D. Pode ter problemas no processamento auditivo", "E. Pode ter Síndrome de Irlen", "F. Pode ranger os dentes", "G. Pode ter Transtorno Obsessivo Compulsivo ou traços dele", "H. Pode ter um ou mais dos seis tipos de Déficit de Atenção", , "I- Normalmente tem dificuldade em funções executivas (por exemplo, Gestão de tempo, planejamento antecipado, organização)", "  J. Pode se balançar, balançar a perna, ficar inquieta ou outros Movimentos com as mãos, enrolar o cabelo, acariciar um tecido macio Para se acalmar", "  K. Pode ser muito sensível a medicamentos, cafeína e/ou álcool", "  L. Pode ter alergia/intolerância a glúten, trigo, caseira ou outros", "  M. Pode ter dificuldade para dormir", "  N. Pode ter Dispraxia", "  O. Pode ter tiques (Por exemplo, limpar a garganta, tossir)"]
    },
    {
        "title":"7-Aparência Física",
        "values":["Normalmente se veste diferente dos seus colegas, muitas vezes de Modo excêntrico, pode se vestir mais pelo conforto do que pela Aparência", "Pode se vestir “bem demais” ou de forma não convencional para Certas ocasiões", " Pode tentar se adequar ao ambiente pela aparência, ou não se Importar nem um pouco", " Pode não tomar banho ou manter a higiene ás vezes, devido ás Diferentes prioridades (normalmente envolvendo interesses Especiais)", " Parece mais nova do que é", " “Pernas inquietas” ou balançar quando está em pé"]
    },
    {
        "title":"8-Estilo de Vida ",
        "values":["Livros, computadores, internet, crianças, natureza podem ser os Melhores amigos dela", "Ela adora ambientes quietos, solidão, paz", "Ela pode ser ultra religiosa ou não ser nem um pouco. Budismo Parece ser comum", "Pode preferir passar o máximo de tempo possível sozinha, com Animais ou na natureza", "Pode ter preferência por rotina e coisas que não mudam dia após Dia", "Tem prazer em fazer o trabalho que escolheu e/ou seus interesses Especiais", "Ela pode fazer de sua maior prioridade arranjar sua vida, eventos, Trabalho e ambiente para evitar situações devastadoras, estressantes Ou perturbadoras"]
    },
    {
        "title":"9-Escolhas de Relacionamentos/Sexualidade/Gênero",
        "values":["Pode namorar ou casar com parceiros muito mais velhos ou muito Mais novos, do mesmo sexo, tendendo a não ver “idade”, “gênero” e Sim a personalidade da pessoa primeiro", "Pode ser assexual, tendo preferencias que julgam mais importantes Que sexo ou um relacionamento", " Pode ser “hipersexual”, fascinada pelo contato sexual", " Pode ser diferente dos seus pares em termos de flexibilidade a Respeito da orientação sexual ou pode pensar em ou querer Mudar de sexo. Alguns indivíduos podem mudar de sexo ou Experimentar com sexualidade como meio de achar sucesso Social ou se ajustar e se sentir menos diferente", " Pode não querer ou precisar de relações intimas (assexual) Tem uma grande flexibilidade e/ou gênero. Pode ser heterossexual, Assexual, gay, bissexual ou transgênero"]
    },
    {
        "title":"10- Interesse Especiais ",
        "values":["  Um interesse especial pode envolver a carreira da pessoa, fantasia, Escrita, animais, leitura – para citar alguns", "  Habilidade em “hiperfocar” por longos períodos de tempo em algo Envolvendo o interesse especial, frequentemente perdendo A noção do tempo", "  Ama e tem prazer em solidão, paz e quietude. Solidão é Frequentemente descrita como “precisando dela como preciso Do ar que respiro”", " Um amor intenso por natureza e animais", " Frequentemente não tem interesse no que outras pessoas acham Interessante", " Pode colecionar ou guardar itens de interesse"]
    },
    {
        "title":"11-Emocional ",
        "values":[" Sente as coisas profundamente", "O humor de outras pessoas a afeta, especialmente se eles são negativos", "Tende a ser muito sensível à dor emocional", "Profundamente comovida por artes, música, alguns filmes", " Vive com ansiedade contínua e generalizada e crises de depressão", " Dificuldade ao regular emoções e controlando stress", "É socialmente e emocionalmente mais jovem/imatura que aqueles em Sua idade cronológica, muito mais jovem se tem vinte e poucos anos", " Ingênua, honesta (normalmente honesta demais)", " Emocionalmente honesta demais (falta de habilidade ou dificuldade em Esconder os sentimentos verdadeiros, quando seria socialmente mais Aceitável se ela o fizesse)", "Sentes emoções intensas de todos os tipos (por exemplo, quando ela Se apaixona profundamente)", , "Ela pode pensar que está tendo compaixão, mas as ações dela podem Não ser interpretadas dessa forma", "Muito sensível e tem muita empatia", "Usualmente conecta e/ou é muito sensível a certos personagens de Filmes", "Muito sensível a problemas que afetam a Terra, animais, direito, Justiça, direitos humanos e os oprimidos"]
    },
    {
        "title":"12-Características de Personalidade e/ou Traços e Habilidades",
        "values":["Uma líder natural, independente, de vontade forte e pode ser Muito competitiva", "Muitos níveis de introversão OU pode ser extrovertida", "Geralmente, não possui um senso forte de si, autoestima e/ou Identidade. Pode usar habilidades de “camaleão” para assimilar E se envolver em uma variedade de grupos ou pessoas diferentes com O passar do tempo, em busca de uma identidade verdadeira", "Tem um grande senso de justiça e integridade, é uma buscadora de Justiça", " Muito criativa e pode ter um turbilhão de ideias originais", " Não gosta de mudanças e pode ficar desorientada e estressada", " Muito sensível a críticas ou o que percebe como criticismo", " Não gosta de ser observada quando deve fazer uma performance", " Podem ter falado para ela que ela se importa demais, faz muito Pelos outros e/ou é muito sensível", " É perfeccionista", " Atenção à detalhes", "Obsessões/interesses especiais podem ser de curto período (mudando De um para outro rapidamente) ou de longo período (podendo fazer Uma ótima carreira)", "Inocência, confiança demais e interpretar outras pessoas literalmente São ingredientes poderosos para sofrer bullying e ser alvo de abusos", "Se sente muito diferente de seus pares, frequentemente descrita Como sendo de outro planeta", "Pode não ter um senso de si mesma e/ou identidade, autoestima", " Tende a ser muito séria, ás vezes séria demais", "  É intensa em tudo o que ela faz", "  Quando criança, pode ter sido descrita como muito sensível e/ou Tímida"]
    },
    {
        "title":"13-Histórico Mental do Passado e/ou Presente",
        "values":["  Pode ter um histórico de chorar muito, sem saber o porquê", "  Pode ter um longo históricos de visitas a terapias, psiquiatras, Psicólogos", "   Pode ter tentado muitos medicamentos", "   Sofre de ansiedade social e transtorno de ansiedade generalizada", "   Pode ter um ou mais dos seis tipos de Déficit de Atenção", "   Apresenta depressão continua e/ou cansaço/exaustão sem saber o Porquê", "    Um histórico de tentativa de entender a si mesma, de achar Respostas para explicar a si mesma e o porquê de ela se sentir Diferente ou não conseguir se encaixar, como mulher", "    Um histórico de muitas visitas a médicos, conselheiros durante a Vida universitária", "    Pode ter um histórico na família de Autismo, Asperger, Bipolaridade, Esquizofrenia, Déficit de Atenção, Transtorno Obsessivo Compulsivo, Desordens de Ansiedade", "    Pode ter sigo diagnosticada erroneamente como bipolar, Personalidade borderline ou esquizofrenia", "Pode ter sigo diagnosticada previamente com desordem de Ansiedade, depressão, transtorno alimentar, personalidade Borderline, bipolar E/ou déficit de atenção", "Histórico de depressão, ansiedade, transtornos alimentares, Alterações extremas de humor"]
    },
    {
        "title":"14-Mecanismos de Cópia",
        "values":["Pode ter recorrido a álcool, drogas, cigarro para conseguir lidar Com emoções intensas, automedicação e/ou socialização/ajustes E/ou ser aceita em um grupo", "Pode usar uma personalidade diferente quando está em público, Para ajudar a lidar com a situação", "Pode ter desenvolvido vários mecanismos de cópia disfuncionais (Por exemplo, arrogância e/ou narcisismo)", "Pode mudar de gênero ou sexualidade como tentativa de se Ajustar e/ou achar um grupo certo", "Usa imitação, escolalia social para fingir que é normal, ou se passar Por normal", "Pode se balançar em pé, sentada, em uma cadeira de balanço Para se acalmar", "Pode precisar se retirar para a cama ou um canto escuro ou um Lugar sozinha para ter privacidade, quietude e administrar Sobrecarga sensorial e/ou social", "Retiro e/ou Esquiva de situações", "Pode desenvolver um transtorno de personalidade como meio de Lidar com a Síndrome de Asperger"]
    },
    {
        "title":"15-Sexto Sentido, Intuição, Habilidades Psíquicas",
        "values":["Tem a habilidade de “sentir” as emoções de outras pessoas", "Pode “saber” de coisas, sem saber como ela obteve o Conhecimento", "Pode trabalhar como “psíquica” ou “médium”"]
    },
    {
        "title":"16-Habilidades Únicas e Pontos Fortes",
        "values":["Inteligente, precisa de conhecimento e ama aprender", "Pode aprender sozinha qualquer coisa que ela coloque na Cabeça", "É teimosa, determinada e independente", "Perfeccionista", "Tem uma memória de longo termo impressionante, memória Fotográfica", "Ótimo senso de humor", "Pode trabalhar muito bem em situação de crise", "Pensa profundamente, muito reflexiva", "Resiliência, uma habilidade para ir de uma crise para outra, Retomar para começar de novo e de novo", "Atenção a detalhes", "Ótima em situações um a um ou apresentando para grupos", "Mais como “filósofas” do que “professoras”, mas pode ser ambas", "Visualiza coisas mentalmente com muitos detalhes, aprende Melhor visualmente", "Pode ter talento com arte, música, escrita, línguas", " Muito intuitiva", " Capaz de pensamentos filosóficos profundos, mulheres com Asperger frequentemente se tornam escritoras, poetas, artistas, Cantoras, atrizes ou professoras"]
    },
    {
        "title":"17-Desafios",
        "values":["  Pode ter dificuldade em entender emoções sutis, por exemplo, Quando alguém sente ciúmes ou está com vergonha, não está Interessado ou está entediado", "  Manter aparências, se passar por normal", "  Controlar emoções", "  Difícil de trabalhar e funcionar dentro de um grupo", "   Muita dificuldade e muito sensível a conflitos, estresse, Discussões, brigas, guerras, fofocas e negatividade Conversa fiada, sem uma “função”, manter amizades e", "   Relacionamentos, ansiedade social ou fobia social", "   Pode gostar ou preferir ficar sozinha o máximo possível", "   Pode achar difícil entender o que os outros esperam dela", "   Outros tiram vantagem dela devido a sua inocência e confiança Nos outros demais", "    Limites (Usualmente quando mais nova)", "    Pode ter dificuldades preenchendo formulários, burocracias (Imposto de renda), controlando dinheiro", "    Pode ter dificuldade reconhecendo ou lembrando de rostos"]
    },
    // {
    //     "title":"",
    //     "values":
    // }
]